language: php

sudo: false

php:
  - '7.0'
  - '7.1'
  - '7.2'

branches:
  only:
      - master

before_install:
  - ./build/tools/composer clear-cache

install: composer install

script:
  - composer test
  - composer sniff
  - composer style

notifications:
  email: false
